{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    rust-overlay.url = "github:oxalica/rust-overlay";
    flake-utils.url = "github:numtide/flake-utils";
    pre-commit-hooks.url = "github:cachix/git-hooks.nix";
    v_flakes.url = "github:valeratrades/v_flakes?ref=v1.6";
    # Brand assets. Not a flake — a pinned source tree we copy the logo out of.
    # "Latest logo" = `nix flake update ev_assets` (bumps flake.lock). Public repo,
    # so this stays token-free.
    ev_assets = { url = "github:EV-invest/assets"; flake = false; };
    # NB: the whitepaper + blog are NOT flake inputs. Both are private repos, and
    # declaring them here forced every `nix run`/`nix develop`/`nix flake check`
    # to authenticate to GitHub just to evaluate. Instead `populate-docs` builds
    # the local sibling clones (../whitepaper, ../blog) at runtime — token-free
    # (their own inputs are public) and best-effort (the frontend still boots if a
    # clone is missing). Refresh = `git -C ../whitepaper pull` etc.
  };
  outputs = { self, nixpkgs, rust-overlay, flake-utils, pre-commit-hooks, v_flakes, ev_assets }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        overlays = [ (import rust-overlay) ];
        pkgs = import nixpkgs {
          inherit system overlays;
          allowUnfree = true;
        };
        #NB: can't load rust-bin from nightly.latest, as there are week guarantees of which components will be available on each day.
        rust = pkgs.rust-bin.selectLatestNightlyWith (toolchain: toolchain.default.override {
          extensions = [ "rust-src" "rust-analyzer" "rust-docs" "rustc-codegen-cranelift-preview" ];
          targets = [ "wasm32-unknown-unknown" ];
        });
        pre-commit-check = pre-commit-hooks.lib.${system}.run (v_flakes.files.preCommit { inherit pkgs; });
        pname = "landing";
        backendCargo = (builtins.fromTOML (builtins.readFile ./backend/Cargo.toml)).package;

        # Brand logo from the pinned `ev_assets` input, copied into the served
        # public dir (gitignored; declaratively populated, never hand-edited).
        logoSrc = "${ev_assets}/logo/logo.svg";

        rs = v_flakes.rs { inherit pkgs rust; };
        github = v_flakes.github {
          inherit pkgs pname rs;
          enable = true;
          lastSupportedVersion = "nightly-2026-05-12";
          containerRelease = { registry = "ghcr.io/EV-invest"; };
          gitignore.extra = ''
            ## frontend/public/ is 100% generated by `nix run` (populate-docs):
            ## source imagery lives in frontend/assets/, while docs/mfe/logo/icons
            ## are built from flake inputs. Nothing under public/ is source.
            frontend/public/
            ## Node / Next.js
            node_modules/
            .next/
            .turbo/
            out/
            *.tsbuildinfo
            ## Env
            .env
            .env.local
            ## Playwright
            test-results/
            playwright-report/
            ## Local DB (nix run .#db / .#dev)
            .pg/
            ## LLMs
            AGENTS.md
            CLAUDE.md
            .claude/
            .pre-commit-config.yaml
          '';
          jobs = {
            warnings.augment = [ "tokei" "code-duplication" ];
            other.augment = [ "loc-badge" ];
          };
          lfs = true;
        };
        readme = v_flakes.readme-fw {
          inherit pkgs pname;
          repo = "EV-invest/landing";
          defaults = true;
          lastSupportedVersion = "nightly-1.92";
          rootDir = ./.;
          # No crate is published yet (the backend is a placeholder), so keep only
          # the badge that always resolves.
          badges = [ "msrv" ];
        };
        combined = v_flakes.utils.combine { inherit rust; modules = [ rs github readme ]; };

        # ── production backend: binary + OCI image ──────────────────────────
        # Built with the dev nightly toolchain (the workspace pins
        # `cargo-features = ["codegen-backend"]`, which stable cargo rejects).
        # `aws-lc-sys` (via reqwest/rustls) needs cmake + libclang; `openssl-sys`
        # (via sentry's native-tls) needs openssl + pkg-config; `.cargo/config`
        # links with mold.
        rustPlatform = pkgs.makeRustPlatform { cargo = rust; rustc = rust; };
        backendSrc = pkgs.lib.cleanSourceWith {
          src = ./.;
          # Cargo only needs the workspace crates + manifests; drop the heavy
          # sibling trees (frontend, target, local DB, vcs) from the build input.
          filter = path: _type:
            ! builtins.elem (baseNameOf path) [ "target" "node_modules" ".pg" ".direnv" ".next" ".git" "frontend" "tmp" "docs" "result" ];
        };
        backendBin = rustPlatform.buildRustPackage {
          pname = backendCargo.name;
          version = backendCargo.version;
          src = backendSrc;
          cargoLock.lockFile = ./Cargo.lock;
          cargoBuildFlags = [ "-p" "backend" "--bin" "backend" ];
          # Drop the `swagger` feature: utoipa-swagger-ui's build script fetches
          # the UI bundle over the network, which the sandbox forbids.
          buildNoDefaultFeatures = true;
          nativeBuildInputs = with pkgs; [ pkg-config cmake perl mold pkgs.rustPlatform.bindgenHook ];
          buildInputs = with pkgs; [ openssl ];
          doCheck = false;
        };
        # ── frontend production image (Next.js standalone) ──────────────────
        # `output: "standalone"` (next.config.ts) emits a self-contained
        # `.next/standalone/server.js` that runs under plain node — no npm at
        # runtime. The committed brand assets are baked into public/; the runtime
        # best-effort docs (whitepaper/blog/portfolio MFE, built from private
        # sibling clones by populate-docs) are intentionally NOT in the image, so
        # those pages degrade — same contract the dev runner already tolerates.
        frontendApp = pkgs.buildNpmPackage {
          pname = "landing-frontend";
          version = "1.0.0";
          src = ./frontend;
          npmDepsHash = "sha256-VeEqSU8km3V5JVfkN5k42/A9LtlFxYmIev04z13z9tU=";
          env.NEXT_TELEMETRY_DISABLED = "1";
          # `npm run build` chains stylelint (a CI lint gate, not an image concern);
          # call next build directly so a style nit can't fail the image. public/ is
          # generated, not committed — stage the brand assets it needs first.
          buildPhase = ''
            runHook preBuild
            mkdir -p public/assets
            cp -rL assets/. public/assets/
            cp -f ${logoSrc} public/assets/logo.svg
            node_modules/.bin/next build
            runHook postBuild
          '';
          # Standalone runtime = server.js + the static chunks + public, side by side.
          installPhase = ''
            runHook preInstall
            mkdir -p $out
            cp -r .next/standalone/. $out/
            cp -r .next/static $out/.next/static
            cp -r public $out/public
            runHook postInstall
          '';
          dontNpmInstall = true;
        };

        # DATABASE_URL arrives via the k8s Secret gitops owns, not baked in.
        # Backend and frontend are separate containers (not one): distinct
        # runtimes/processes, and so each rolls out + restarts independently —
        # a frontend crash or deploy never touches the API.
        containerStd = v_flakes.container.implement {
          inherit pkgs pname;
          # backend (Axum API)
          containers."" = {
            port = 58844;
            healthPath = "/api/v1/health";
            criticality = "high";
            entrypoint = [ "/bin/backend" ];
            contents = [ backendBin ];
            imageEnv = [ "BIND_ADDR=0.0.0.0:58844" "APP_ENV=production" ];
          };
          # frontend (Next.js marketing site) → image `landing-frontend`.
          containers.frontend = {
            port = 58843;
            healthPath = "/";
            criticality = "high";
            entrypoint = [ "${pkgs.nodejs}/bin/node" "${frontendApp}/server.js" ];
            contents = [ pkgs.nodejs frontendApp ];
            workingDir = "${frontendApp}";
            imageEnv = [ "PORT=58843" "HOSTNAME=0.0.0.0" "NODE_ENV=production" ];
          };
        };

        # ── shared shims ────────────────────────────────────────────────────
        # rust-lld (wasm32 linker) embeds the wrong rpath on macOS — it looks for
        # libLLVM.dylib in bin/../lib/ but Nix puts it one level up in lib/. The
        # FALLBACK var only kicks in when normal resolution fails. Kept ready for
        # the Rust backend that grows under backend/.
        dyldFallback = ''export DYLD_FALLBACK_LIBRARY_PATH="${rust}/lib''${DYLD_FALLBACK_LIBRARY_PATH:+:$DYLD_FALLBACK_LIBRARY_PATH}"'';
        # tonic-build / prost-build shell out to protoc; point them at nixpkgs'.
        protocEnv = ''export PROTOC="${pkgs.protobuf}/bin/protoc"'';

        # ── served docs (whitepaper + blog) ─────────────────────────────────
        # Populate frontend/public/ with the logo (from the public ev_assets
        # input) and the typst-built whitepaper/blog HTML+PDF. The docs come from
        # the LOCAL sibling clones (../whitepaper, ../blog) built at runtime —
        # token-free (those repos are private, but their flake inputs are public)
        # and best-effort: a missing clone or a failed build only warns, so the
        # frontend always boots and the doc pages degrade to a graceful
        # "unavailable"/last-good state. Idempotent (nix caches the builds).
        populateDocs = pkgs.writeShellApplication {
          name = "populate-docs";
          runtimeInputs = with pkgs; [ git nix coreutils ];
          text = ''
            repo="$(git rev-parse --show-toplevel)"
            pub="$repo/frontend/public"
            mkdir -p "$pub/assets" "$pub/blogs"
            # public/ is 100% generated; the only committed source is
            # frontend/assets/ (section imagery). Stage it plus the brand logo
            # (also the manifest + JSON-LD icon) into the served public/assets/.
            cp -rL "$repo/frontend/assets/." "$pub/assets/"
            cp -f ${logoSrc} "$pub/assets/logo.svg"
            chmod -R u+w "$pub/assets"

            wp=""
            if [ -d "$repo/../whitepaper" ]; then
              wp="$(nix build "$repo/../whitepaper" --no-link --print-out-paths 2>/dev/null || true)"
              [ -n "$wp" ] || echo "warn: whitepaper build failed — /whitepaper will degrade" >&2
            else
              echo "warn: ../whitepaper not checked out — /whitepaper will degrade" >&2
            fi
            if [ -n "$wp" ]; then
              [ -e "$wp/whitepaper.pdf" ]        && cp -f "$wp/whitepaper.pdf"        "$pub/whitepaper.pdf"
              [ -e "$wp/whitepaper.light.html" ] && cp -f "$wp/whitepaper.light.html" "$pub/whitepaper.light.html"
              [ -e "$wp/whitepaper.dark.html" ]  && cp -f "$wp/whitepaper.dark.html"  "$pub/whitepaper.dark.html"
            fi

            bl=""
            if [ -d "$repo/../blog" ]; then
              bl="$(nix build "$repo/../blog" --no-link --print-out-paths 2>/dev/null || true)"
              [ -n "$bl" ] || echo "warn: blog build failed — /blogs will degrade" >&2
            else
              echo "warn: ../blog not checked out — /blogs will degrade" >&2
            fi
            if [ -n "$bl" ]; then
              for dir in "$bl"/*/; do
                [ -d "$dir" ] || continue
                slug="$(basename "$dir")"
                [ -e "$dir/main.pdf" ]        && cp -f "$dir/main.pdf"        "$pub/blogs/''${slug}.pdf"
                [ -e "$dir/main.light.html" ] && cp -f "$dir/main.light.html" "$pub/blogs/''${slug}.light.html"
                [ -e "$dir/main.dark.html" ]  && cp -f "$dir/main.dark.html"  "$pub/blogs/''${slug}.dark.html"
              done
            fi

            # Real-estate MFE bundle (the `embeds` artifact from the sibling REA
            # repo), baked into public/ and served same-origin at /mfe — the host
            # owns the bundle's static assets; REA's container no longer serves it.
            mfe=""
            if [ -d "$repo/../real_estate_allocation" ]; then
              mfe="$(nix build "$repo/../real_estate_allocation#embeds" --no-link --print-out-paths 2>/dev/null || true)"
              [ -n "$mfe" ] || echo "warn: real-estate embed build failed — portfolio MFE will degrade" >&2
            else
              echo "warn: ../real_estate_allocation not checked out — portfolio MFE will degrade" >&2
            fi
            if [ -n "$mfe" ]; then
              rm -rf "$pub/mfe"; mkdir -p "$pub/mfe"
              cp -rL "$mfe"/. "$pub/mfe/"
              chmod -R u+w "$pub/mfe"
            fi

            # nix-store copies land read-only; make them writable so a later run
            # can overwrite. Tolerate an empty glob.
            chmod -f u+w "$pub"/whitepaper.* "$pub"/blogs/* 2>/dev/null || true
          '';
        };

        # ── frontend (Next.js marketing site) ───────────────────────────────
        # Standalone npm app under frontend/. `npm install` generates/updates the
        # lockfile and installs into frontend/node_modules on first run.
        runFrontend = pkgs.writeShellApplication {
          name = "run-frontend";
          runtimeInputs = with pkgs; [ nodejs git ];
          text = ''
            ${populateDocs}/bin/populate-docs || true
            repo="$(git rev-parse --show-toplevel)"
            cd "$repo/frontend"
            [ -d node_modules/next ] || npm install
            exec npm run dev
          '';
        };

        # ── backend (Axum API) ──────────────────────────────────────────────
        # Needs a Postgres (use `.#db` or `.#dev`). Every other integration
        # (SMTP, Sentry, PostHog) is a no-op until its env is set, so the bare
        # default just boots against the local trust-auth cluster.
        runBackend = pkgs.writeShellApplication {
          name = "run-backend";
          runtimeInputs = with pkgs; [ rust git ];
          text = ''
            ${dyldFallback}
            repo="$(git rev-parse --show-toplevel)"
            cd "$repo"
            export DATABASE_URL="''${DATABASE_URL:-postgres://postgres@localhost:5432/ev_landing}"
            export BIND_ADDR="''${BIND_ADDR:-0.0.0.0:58844}"
            export RUST_LOG="''${RUST_LOG:-info,backend=debug}"
            export APP_ENV="''${APP_ENV:-development}"
            exec cargo run -p backend
          '';
        };

        # ── local Postgres ──────────────────────────────────────────────────
        # Project-local dev database. Cluster data + unix sockets live under
        # .pg/ at the repo root (gitignored). First run initdb's a trust-auth
        # cluster and creates `ev_landing`; later runs just start the server.
        # Listens on 127.0.0.1:5432 — matches backend/.env.example.
        runPostgres = pkgs.writeShellApplication {
          name = "run-postgres";
          runtimeInputs = with pkgs; [ postgresql git coreutils gnugrep ];
          text = ''
            repo="$(git rev-parse --show-toplevel)"
            export PGDATA="$repo/.pg/data"
            sockets="$repo/.pg/sockets"
            port="''${PGPORT:-5432}"
            db="''${PGDATABASE:-ev_landing}"

            mkdir -p "$sockets"
            if [ ! -s "$PGDATA/PG_VERSION" ]; then
              echo "initialising postgres cluster in $PGDATA"
              initdb --username=postgres --auth=trust --pgdata="$PGDATA" >/dev/null
            fi
            # Postgres refuses to start unless PGDATA is 0700/0750 — clamp it.
            chmod 0700 "$PGDATA"

            (
              until pg_isready --host="$sockets" --port="$port" --quiet; do sleep 0.2; done
              if ! psql --host="$sockets" --port="$port" --username=postgres --dbname=postgres \
                     --tuples-only --no-align \
                     --command "SELECT 1 FROM pg_database WHERE datname='$db'" | grep -q 1; then
                createdb --host="$sockets" --port="$port" --username=postgres "$db"
                echo "created database '$db'"
              fi
              echo "postgres ready on 127.0.0.1:$port (db '$db', user 'postgres', trust auth)"
            ) &

            exec postgres -D "$PGDATA" -k "$sockets" -h 127.0.0.1 -p "$port"
          '';
        };

        # ── contract codegen ────────────────────────────────────────────────
        # `nix run .#gen-api` → dump the Rust/utoipa OpenAPI spec to
        # backend/openapi.json, then regenerate the TS client from it. Run after
        # changing any DTO or handler signature; commit both the spec and client.
        runGenApi = pkgs.writeShellApplication {
          name = "run-gen-api";
          runtimeInputs = with pkgs; [ rust nodejs git ];
          text = ''
            ${dyldFallback}
            repo="$(git rev-parse --show-toplevel)"
            cd "$repo"
            echo "▶ dumping OpenAPI spec → backend/openapi.json"
            cargo run --quiet --bin gen_openapi > backend/openapi.json
            echo "▶ generating TS client → frontend/shared/api/generated"
            cd frontend
            [ -d node_modules/.bin ] || npm install
            npm run gen:api
          '';
        };

        # ── dev orchestrator ────────────────────────────────────────────────
        # `nix run .#dev` → Postgres + backend + frontend. Postgres starts first;
        # the backend launches once it accepts connections. One trap tears the
        # whole tree down on Ctrl-C / exit.
        runDev = pkgs.writeShellApplication {
          name = "run-dev";
          runtimeInputs = with pkgs; [ postgresql git coreutils ];
          text = ''
            pids=()
            cleanup() {
              echo; echo "shutting down dev stack…"
              [ ''${#pids[@]} -gt 0 ] && kill "''${pids[@]}" 2>/dev/null || true
              wait 2>/dev/null || true
            }
            trap cleanup EXIT INT TERM

            echo "▶ postgres"
            ${runPostgres}/bin/run-postgres & pids+=($!)

            echo "  waiting for postgres on 127.0.0.1:''${PGPORT:-5432}…"
            until pg_isready --host=127.0.0.1 --port="''${PGPORT:-5432}" --quiet; do sleep 0.3; done

            echo "▶ backend  (:58844)"
            ${runBackend}/bin/run-backend & pids+=($!)
            echo "▶ frontend (:58843)"
            ${runFrontend}/bin/run-frontend & pids+=($!)

            wait
          '';
        };
      in
      {
        # `nix run .#dev`      → Postgres + backend + frontend
        # `nix run .#frontend` → Next.js marketing site (:58843)
        # `nix run .#backend`  → Axum API only (:58844, needs a DB: `.#db` or `.#dev`)
        # `nix run .#db`       → local Postgres only (:5432)
        # `nix run .#gen-api`  → regenerate openapi.json + the TS client
        apps = {
          dev = { type = "app"; program = "${runDev}/bin/run-dev"; };
          frontend = { type = "app"; program = "${runFrontend}/bin/run-frontend"; };
          backend = { type = "app"; program = "${runBackend}/bin/run-backend"; };
          db = { type = "app"; program = "${runPostgres}/bin/run-postgres"; };
          gen-api = { type = "app"; program = "${runGenApi}/bin/run-gen-api"; };
        };

        packages = {
          default = backendBin;
          backend = backendBin;
        } // containerStd.packages;

        containers = containerStd.containers;

        devShells.default =
          with pkgs;
          mkShell {
            shellHook =
              pre-commit-check.shellHook
              + combined.shellHook
              + ''
                cp -f ${(v_flakes.files.treefmt) { inherit pkgs; }} ./.treefmt.toml
                # Logo + whitepaper/blog docs into public/ (token-free, best-effort).
                ${populateDocs}/bin/populate-docs || true

                ${dyldFallback}
                ${protocEnv}
              '';

            packages = [
              nodejs
              openssl
              pkg-config
              protobuf
              clang-tools
              rust
              mold
              sccache
              postgresql
              playwright-driver.browsers
            ] ++ pre-commit-check.enabledPackages ++ combined.enabledPackages;

            env.RUST_BACKTRACE = 1;
            env.RUST_LIB_BACKTRACE = 0;

            # Shared compile cache across builds; incremental off (sccache can't cache it).
            env.RUSTC_WRAPPER = "sccache";
            env.CARGO_INCREMENTAL = "0";

            # Playwright (frontend visual tests): drive the nixpkgs browsers instead
            # of the npm-downloaded ones (those dynamically link libs absent on
            # NixOS). The frontend `@playwright/test` version MUST match
            # playwright-driver's or the browser revisions won't line up.
            env.PLAYWRIGHT_BROWSERS_PATH = "${pkgs.playwright-driver.browsers}";
            env.PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1";
            env.PLAYWRIGHT_HOST_PLATFORM_OVERRIDE = "nixos";
          };
      }
    );
}
