// Shell-injecting HTML proxy for zone mounts (PATTERNS.md §9). Only zone HTML
// flows through here — asset/API traffic stays on native beforeFiles rewrites
// (next.config.ts). The zone emits a chromeless full document; this hop inserts
// the conductor-owned AppShell into the initial HTML stream: header assets
// after `<head…>`, the static header fragment after `<body…>`, everything else
// piped through raw. Zones stay fully SSR'd and know nothing about the shell.
//
// Injection is same-origin `<link>`/`<script src>` + static markup only — never
// inline code, so zone CSPs (`script-src 'self' 'nonce-…'`) pass untouched.
import { Buffer } from "node:buffer";

// Generated by scripts/build-shell.mts (predev/prebuild); statically imported
// so the standalone output traces it and the per-request cost is one concat.
import shell from "./zone-shell.generated.json";

const HOP_BY_HOP = [
  "connection",
  "keep-alive",
  "transfer-encoding",
  "upgrade",
  "proxy-authenticate",
  "proxy-authorization",
  "te",
  "trailer",
];

// CSS in head → the header paints with the first frame: zero FOUC/CLS.
const HEAD_INSERT = `<link rel="stylesheet" href="${shell.css}"><script defer src="${shell.js}"></script>`;
const BODY_INSERT = shell.fragment;

export async function proxyZone(
  request: Request,
  zoneUrl: string | undefined
): Promise<Response> {
  // Env unset ⇒ zone disabled: 404 rather than half-proxying, preserving the
  // old rewrite-less semantics.
  if (!zoneUrl) return new Response(null, { status: 404 });

  const url = new URL(request.url);
  const target = zoneUrl.replace(/\/+$/, "") + url.pathname + url.search;

  const headers = new Headers(request.headers);
  for (const name of HOP_BY_HOP) headers.delete(name);
  // Let fetch derive Host from the target, as the native rewrite proxy does;
  // the public host travels in x-forwarded-host.
  headers.delete("host");
  // Uncompressed internal hop: conductor re-compresses egress, so injection
  // never has to decompress-transform-recompress.
  headers.set("accept-encoding", "identity");
  // Preserve an outer proxy's forwarding headers; originate them when the
  // conductor is the edge.
  if (!headers.has("x-forwarded-host"))
    headers.set("x-forwarded-host", url.host);
  if (!headers.has("x-forwarded-proto"))
    headers.set("x-forwarded-proto", url.protocol.replace(":", ""));

  const hasBody = request.method !== "GET" && request.method !== "HEAD";
  let upstream: Response;
  try {
    upstream = await fetch(target, {
      method: request.method,
      headers,
      // Redirects pass through to the browser: the zone already emits
      // basePath'd Locations (e.g. /cabinet/login).
      redirect: "manual",
      ...(hasBody ? { body: request.body, duplex: "half" } : {}),
    } as RequestInit);
  } catch {
    // No fallback content — upstream unreachable is an error, stated plainly.
    return new Response("502 Bad Gateway: zone upstream unreachable", {
      status: 502,
      headers: { "content-type": "text/plain; charset=utf-8" },
    });
  }

  const resHeaders = new Headers();
  upstream.headers.forEach((value, name) => {
    // content-length/-encoding: injection changes the length, and the identity
    // hop means encoding never applies; the runtime re-frames the response.
    if (HOP_BY_HOP.includes(name)) return;
    if (name === "content-length" || name === "content-encoding") return;
    if (name === "set-cookie") return; // appended individually below
    resHeaders.set(name, value);
  });
  for (const cookie of upstream.headers.getSetCookie())
    resHeaders.append("set-cookie", cookie);

  // Anything that isn't an HTML document (RSC payloads, files) streams through
  // byte-identical. Error HTML keeps its chrome — inject on 4xx/5xx too.
  const isHtml = (upstream.headers.get("content-type") ?? "").includes(
    "text/html"
  );
  const body =
    isHtml && upstream.body
      ? upstream.body.pipeThrough(shellInjector())
      : upstream.body;
  return new Response(body, {
    status: upstream.status,
    statusText: upstream.statusText,
    headers: resHeaders,
  });
}

// Scan cap: a document whose <head…>/<body…> open tags haven't both appeared
// within this many bytes is streamed on unmodified rather than buffered.
const SCAN_CAP = 64 * 1024;

/** Streams bytes through, inserting {@link HEAD_INSERT} after the `<head…>`
 *  open tag and {@link BODY_INSERT} after `<body…>`. Only what's needed to
 *  finish a match is withheld (a tag split across chunks, or an open tag whose
 *  `>` hasn't arrived); everything else flows the moment it's scanned. */
function shellInjector(): TransformStream<Uint8Array, Uint8Array> {
  const encoder = new TextEncoder();
  let carry = Buffer.alloc(0);
  let scanned = 0;
  // 0: seeking <head…>, 1: seeking <body…>, 2: passthrough.
  let phase = 0;
  const tags = ["<head", "<body"];
  const inserts = [encoder.encode(HEAD_INSERT), encoder.encode(BODY_INSERT)];

  const scan = (controller: TransformStreamDefaultController<Uint8Array>) => {
    while (phase < 2) {
      // A document whose open tags haven't appeared within the cap gets the
      // rest streamed unmodified — never buffer past it.
      if (scanned > SCAN_CAP) {
        phase = 2;
        break;
      }
      const tag = tags[phase];
      const lower = carry.toString("latin1").toLowerCase();
      let from = 0;
      let idx = -1;
      // Find a real open tag: `<head` must not be the prefix of `<header…>`.
      for (;;) {
        idx = lower.indexOf(tag, from);
        if (idx === -1) break;
        const next = lower[idx + tag.length];
        if (
          next === undefined ||
          next === ">" ||
          next === "/" ||
          /\s/.test(next)
        )
          break;
        from = idx + 1;
      }
      if (idx === -1) {
        // Emit all but a possible split-tag tail.
        const keep = Math.min(carry.length, tag.length - 1);
        if (carry.length > keep) {
          controller.enqueue(carry.subarray(0, carry.length - keep));
          carry = carry.subarray(carry.length - keep);
        }
        return;
      }
      const close = lower.indexOf(">", idx + tag.length);
      if (close === -1) {
        // Open tag seen but not closed yet: emit up to the tag, hold the rest.
        if (idx > 0) {
          controller.enqueue(carry.subarray(0, idx));
          carry = carry.subarray(idx);
        }
        return;
      }
      controller.enqueue(carry.subarray(0, close + 1));
      controller.enqueue(inserts[phase]);
      carry = carry.subarray(close + 1);
      phase += 1;
    }
    if (carry.length > 0) {
      controller.enqueue(carry);
      carry = Buffer.alloc(0);
    }
  };

  return new TransformStream<Uint8Array, Uint8Array>({
    transform(chunk, controller) {
      if (phase === 2 && carry.length === 0) {
        controller.enqueue(chunk);
        return;
      }
      carry =
        carry.length === 0 ? Buffer.from(chunk) : Buffer.concat([carry, chunk]);
      scanned += chunk.length;
      scan(controller);
    },
    flush(controller) {
      if (carry.length > 0) controller.enqueue(carry);
    },
  });
}
